# 1. Remova espaços no nome da aplicação (pode causar erro em alguns logs/ferramentas)
spring.application.name=gerenciamento-produtos-categorias

# 2. No Postgres, evite o hífen "-" no nome do banco de dados na URL. 
# O padrão SQL prefere underscore "_". Se usar hífen, você teria que criar o banco 
# com aspas duplas no SQL, o que dá dor de cabeça. Use assim:
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gerenciamento_produtos_categorias
spring.datasource.username=postgres
spring.datasource.password=0000

# Configurações de JPA e Hibernate (Estão ótimas!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true